name: dependencyBot
on:
  schedule:
    - cron:  '00 1 * * *'
  workflow_dispatch:

jobs:
  # PRs must be closed and re-opened to trigger checks - see here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
  CAMB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY_ACTIONS }}
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: aux/dependencies.yml
          version_name: camb
          repo: cmbant/CAMB
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [dependencyBot](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          assignees: abensonca
  forutils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY_ACTIONS }}
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: aux/dependencies.yml
          version_name: forutils
          repo: cmbant/forutils
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [dependencyBot](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          assignees: abensonca
  CLASS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY_ACTIONS }}
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: aux/dependencies.yml
          version_name: class
          repo: lesgourg/class_public
          tag: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [dependencyBot](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          assignees: abensonca
  FSPS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY_ACTIONS }}
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: aux/dependencies.yml
          version_name: fsps
          repo: cconroy20/fsps
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "fix(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [dependencyBot](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          assignees: abensonca
