name: 'PR-Checks'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
  concurrency:
  group: prCheck-${{ github.ref }}
  cancel-in-progress: true  
defaults:
  run:
    shell: bash
jobs:
  # Validate YAML
  Validate-YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          apt -y update
          apt install -y yamllint
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.yml
      - name: Validate any YAML files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "Validating YAML file: $file"
            yamllint $file
          done
